services:
    postgres:
        image: postgres:16
        environment:
            POSTGRES_USER: chat
            POSTGRES_PASSWORD: chat
            POSTGRES_DB: chat
        ports: ["5432:5432"]
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U chat"]
            interval: 5s
            timeout: 5s
            retries: 10

    redis:
        image: redis:7
        ports: ["6379:6379"]

    api:
        build: ./apps/api
        env_file: .env
        environment:
            API_PORT: 3001
            REDIS_URL: redis://redis:6379
            DATABASE_URL: postgresql://chat:chat@postgres:5432/chat
        ports: ["3001:3001"]
        depends_on: [postgres, redis]

    web:
        build: ./apps/web
        env_file: .env
        environment:
            NEXT_PUBLIC_SOCKET_URL: http://localhost:3001
        ports: ["3000:3000"]
        depends_on: [api]
